### PR TITLE
[16.0][FW] storage_backend_sftp: fix move_files

### PR DESCRIPTION
**Pull request by thienvh332**
Port of `#262` from `14.0` to `16.0`.

The following PRs have been blacklisted:
- #: False positive
- `#78`: (auto) Nothing to port from `PR #78`
- `#106`: (auto) Nothing to port from `PR #106`

### CODE REVIEW

**Comment by nilshamerlinck** [comment]
that's a lot of commits for only some ports, no?

**Comment by thienvh332** [comment]
> that's a lot of commits for only some ports, no?

Hi sir,
Those individual commits are all commits that were rebased during the migration from v14 to v15 to v16. So they are not necessary to add.

**Comment by thienvh332** [comment]
Replaced by: https://github.com/thienvh332/storage/pull/13

**Comment by thienvh332** [comment]
Hi sir,
I don't know why this PR wasn't updated when the 16.0 branch was updated? So I created a new PR for it.

**Pull request closed without merging**
